name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # This will checkout all submodules

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Authenticate with GitHub Packages
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/tmsampson/index.json" \
          --name "github" \
          --username YOUR_GITHUB_USERNAME \
          --password ${{ secrets.SCRIBANTER_PUBLISH_TOKEN }} \
          --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build Src/Scribanter/Scribanter.csproj --configuration Release --no-restore

    - name: Pack Core Library
      run: dotnet pack Src/Scribanter/Scribanter.csproj --configuration Release --output .

    - name: Push Package to GitHub Packages
      run: dotnet nuget push Scribanter.*.nupkg --source "github" --api-key ${{ secrets.SCRIBANTER_PUBLISH_TOKEN }} --skip-duplicate