name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # This will checkout all submodules

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Src/Scribanter.sln

      - name: Build solution
        run: dotnet build Src/Scribanter.sln --no-restore

      - name: Run tests
        run: dotnet test Src/Scribanter.sln --logger \"console;verbosity=normal\""